[fcitx5-pinyin-zhwiki]
src.archpkg = "fcitx5-pinyin-zhwiki"
src.prefix = "0.2.4."
fetch.url = "https://github.com/felixonmars/fcitx5-pinyin-zhwiki/releases/download/0.2.4/zhwiki-$ver.dict"

[fcitx5-pinyin-moegirl]
src.github = "outloudvi/mw2fcitx"
fetch.url = "https://github.com/outloudvi/mw2fcitx/releases/download/$ver/moegirl.dict"

[rime-ice]
src.git = "https://github.com/iDvel/rime-ice"
fetch.github = "iDvel/rime-ice"

[catppuccin-fcitx5]
src.git = "https://github.com/catppuccin/fcitx5"
fetch.github = "catppuccin/fcitx5"

[librime-charcode]
src.git = "https://github.com/rime/librime-charcode.git"
fetch.github = "rime/librime-charcode"

[librime-lua]
src.git = "https://github.com/hchunhui/librime-lua"
fetch.github = "hchunhui/librime-lua"

[librime-octagram]
src.git = "https://github.com/lotem/librime-octagram.git"
fetch.github = "lotem/librime-octagram"

[librime-proto]
src.git = "https://github.com/lotem/librime-proto.git"
fetch.github = "lotem/librime-proto"

[catppuccin-fish]
src.git = "https://github.com/catppuccin/fish"
fetch.github = "catppuccin/fish"

